### ISSUE TITLE
Cannot open SVG in Adobe Illustrator: This SVG is invalid. Validate before Opening

### ISSUE THREAD

**Issue by dringel** [sharonchoong/svg-exportJS#10]
Hello,
I tried to export an SVG container from my website. The file is downloaded, but I cannot open it in Adobe Illustrator. I get the error This SVG is invalid. Validate before Opening. What might be the reason? The PNG export works fine.

Thanks!

Daniel

**Comment by sharonchoong** [comment]
I suspect that there are invalid elements in that SVG, but OP hasn't provided the SVG in question.
