### ISSUE TITLE
PullRequest:  Add callback function after Download

### ISSUE THREAD

**Issue by SarahTrees** [sharonchoong/svg-exportJS#17]
Background
For one project it was necessary to export several SVGs one after the other as separate files. To do this, each SVG had to be created, then edited and then exported.
Since downloadSvg works asyncronously, I needed a feedback when the triggerDownload is completed. After that I can now change my SVG and then start a new export.

Update svg-export.js
I added an event "onDone" that fires when triggerDownload is finished, i.e. when it is ok to change the original SVG.

Please check the PullRequest. Thank you very much!

**Comment by sharonchoong** [comment]
Thank you for your contribution!
