### ISSUE TITLE
Not working for SVG Pattern

### ISSUE THREAD

**Issue by keshavnaidu** [sharonchoong/svg-exportJS#5]
First of all, its wonderful app...
But, Its not working while exporting a PDF, When we use a SVG pattern example this pattern:

`<svg id="mysvg" xmlns="http://www.w3.org/2000/svg" width="595.28" height="841.89">
  <pattern width="40" height="40" patternUnits="userSpaceOnUse" id="a" viewBox="0 -40 40 40" overflow="visible">
    <path fill="none" d="M0 0h40v-40H0z"/>
    <path fill="#1D0E82" d="M0-40v20h20v-20zM20-20V0h20v-20z"/>
  </pattern>
  <g fill="#1D0E82">
    <path d="M457-99h20v20h-20zM477-79h20v20h-20z"/>
  </g>
  <path fill="url(#a)" d="M0 0h595.28v841.89H0z"/>
</svg>`

Any help will be appreciated.. 
Thanks

**Comment by sharonchoong** [comment]
Hi! Thanks for  When exporting to pdf, we are using SVG-to-PDFKit, but the jsdelivr CDN and the npm package for that are outdated.  Please feel free to get a copy of the latest version of SVG-to-PDFKit directly from the [repo](https://github.com/alafr/SVG-to-PDFKit/blob/master/source.js) (it is under MIT license), and save it to your project. I will also update the readme and demo with a SVG pattern example.
