### ISSUE TITLE
Images are removed while exporting as pdf

### ISSUE THREAD

**Issue by DhineshKSD** [sharonchoong/svg-exportJS#6]

**Comment by sharonchoong** [comment]
Please provide a code sample or description of the issue.

**Comment by DhineshKSD** [comment]
>var svg = d3
  .select("body")
  .append("svg")
  .attr("id", "svg")
  .attr("width", 200)
  .attr("height", 200)
  .append("image")
  .attr("xlink:href", "https://i.stack.imgur.com/NVExJ.png")

> function download() {
  svgExport.downloadPdf(document.getElementById("svg"), "Circles and rectangles chart", {
    pdfOptions: {
      chartCaption: "Hi there.  This is a test chart caption. ",
    },
  });
}


The block1 is the script that has an image. I am trying to export the image using the downloadPdf method (block2) but the image is not showing up on the generated PDF.

**Comment by sharonchoong** [comment]
This was on the roadmap (thanks for the reminder); I just finished working on it.  The new release of svg-export now supports exporting svg containing images. Please see the README for more info, and the demo for an example.

**Comment by DhineshKSD** [comment]
@sharonchoong 

Can you please provide some examples for enabling allowCrossOriginImage

**Comment by sharonchoong** [comment]
You would just set it to true. For example, 
```
svgExport.downloadPdf(svgString, "chart title name", {
  width: 200,
  height: 200,
  allowCrossOriginImage: true
});
```
However, the image host server must also have allowed cross-origin access on their end.
