### ISSUE TITLE
Export multiple SVG files into one PDF

### ISSUE THREAD

**Issue by paopre** [sharonchoong/svg-exportJS#9]
Hello,

is it possible to export multiple SVG files into ONE pdf ? 

Thanks

**Comment by sharonchoong** [comment]
Currently svg-exportJS exports one SVG at a time.  When exporting multiple SVGs into one PDF, you may have specific requirements as to the position and size of each SVG image in the resulting PDF.  So it would be best if you could use Javascript to combine your SVGs into one SVG with your desired positions/sizing, then export it to PDF using svg-exportJS.
